function [contrasts] = make_contrasts(this_subject)

beta_dir_absolute = sprintf(fullfile(...
    BaseDir(), ...
    'subjects', ...
    'Subject%0.3d', ...
    'SPM_analysis'), ...
    this_subject.SubjectNum);
betaFiles = dir([beta_dir_absolute, '/beta_*']);

%% create contrasts
% WordType specific
Nbetas = length(betaFiles);
WordType = {'person', 'building', 'tool'};
contrast = zeros(length(WordType), Nbetas);
sess_info = parseOneSession(this_subject.SubjectNum);
for i = 1:length(sess_info)
    trial_wordtype = sess_info{i}.data(strcmp(sess_info{i}.varnames, 'wordType'));
    Ntrials = length(trial_wordtype{1});
    for j = 1:length(WordType)
        contrast(j, (i-1)*Ntrials+1:i*Ntrials) = strcmp(trial_wordtype{:}, WordType{j});
    end
end


contrasts = struct(...
    'name', ...
    {'person', 'building', 'tool', ...
    'person > building', 'person > tool', 'building > person', 'building > tool', 'tool > person', 'tool > building'} ,...
    'vec', ...
    {contrast(1, :), contrast(2, :), contrast(3, :), ...
    contrast(1, :) - contrast(2, :), contrast(1, :) - contrast(3, :), ...
    contrast(2, :) - contrast(1, :), contrast(2, :) - contrast(3, :), ...
    contrast(3, :) - contrast(1, :), contrast(3, :) - contrast(2, :)});