function dataOut = parseScanBehavData(fn) 
%% read in data from file, returning a struct with fields data and varnames

% version 1 wordlist: used on subject 1 & 2
%{
WordList = cellstr(reshape({'doctor', 'hospital', 'stethoscope', ... 
    'soldier', 'fort', 'gun',...
    'farmer', 'barn', 'plow',...
    'mechanic', 'garage', 'wrench',...
    'photographer', 'studio', 'camera', ...
    'butcher', 'slaughterhouse', 'cleaver', ...
    'teacher', 'school', 'chalk', ... 
    'chef', 'restaurant', 'skillet', ...
    'priest', 'church', 'bible', ...
    'knight', 'castle', 'sword',... 
    'Eskimo', 'Igloo', 'harpoon',...
    'bodybuilder', 'gym', 'dumbbell',...
    'gardener', 'greenhouse', 'mower', ...
    'shopper', 'mall', 'cart',...
    'Judge', 'court', 'gavel',...
    'blacksmith', 'forge', 'anvil',...
    'hairdresser', 'barbershop', 'trimmer',...
    'chemist', 'laboratory', 'beaker',...
    'canoeist', 'boathouse', 'paddle' ...
    }, 3, 19)');
%}
WordList = cellstr(reshape({'doctor', 'hospital', 'stethoscope', ... 
    'soldier', 'fort', 'gun',...
    'farmer', 'barn', 'plow',...
    'mechanic', 'garage', 'wrench',...
    'photographer', 'studio', 'camera', ...
    'teacher', 'school', 'chalk', ... 
    'chef', 'restaurant', 'skillet', ...
    'knight', 'castle', 'sword',... 
    'Eskimo', 'Igloo', 'harpoon',...
    'bodybuilder', 'gym', 'dumbbell',...
    'gardener', 'greenhouse', 'mower', ...
    'shopper', 'mall', 'cart',...
    'Judge', 'court', 'gavel',...
    'hairdresser', 'barbershop', 'trimmer',...
    'chemist', 'laboratory', 'beaker'...
    }, 3, 15)');
    
WordType = {'person', 'building', 'tool'};

dataTable = readtable(fn, 'HeaderLines', 1, 'delimiter', '\t');

% data cleaning
dataTable = dataTable(~isnan(dataTable.Display_on_sec) | ~isnan(dataTable.Display_off_sec), :);
dataTable.onsetTime = floor(dataTable.Display_on_sec);
dataTable.duration = round(dataTable.Display_off_sec - dataTable.Display_on_sec);
dataTable.trialNum = (1:size(dataTable, 1))';
dataTable.Response = []; % don't deal with Responses for now

% for now, don't care about control trials
%dataTable = dataTable(isnan(dataTable.Response), :);


for i = 1:length(WordType)
    Nwords = sum(ismember(dataTable.Stimulus, WordList(:,i)));
    dataTable(ismember(dataTable.Stimulus, WordList(:,i)), 'wordType') = ...
        cellstr(repmat((WordType{i}), Nwords, 1));
end

% dump words that are not in the list
%dataTable = dataTable(~cellfun('isempty', dataTable.wordType), :);

wordList_reshaped = reshape(WordList, [], 1);
stimCategory = nan(size(dataTable, 1), 1);
for i = 1:length(wordList_reshaped)
    idx = ismember(dataTable.Stimulus, wordList_reshaped{i});
    stimCategory(idx) = mod(i, size(WordList, 1)) + 1;
end
dataTable.stimCategory = stimCategory;
dataTable.actualTrials = ~isnan(stimCategory);
dataOut = struct();

dataOut.varnames = dataTable.Properties.VariableNames;
for i = 1:size(dataTable, 2)
    dataOut.data{i} = dataTable{:, i};
end